// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mfrihcfcznoytqbfewyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1mcmloY2Zjem5veXRxYmZld3l6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMDM0MDEsImV4cCI6MjA1Njg3OTQwMX0.IOnMGZPJH76wb-qwh0g7edXIcjdrJRz_9q9j7ddD2Ic";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);